# Module 1 — Basics of PyTorch & TensorFlow
### Assignment 1: Tensor Creation and Basic Operations
1. Create the following tensors:
a. A 1D tensor [1, 2, 3, 4]
b. A 2D tensor of shape (3, 3) with random values
c. A tensor of zeros of shape (2, 5)
2. Perform addition, subtraction, and multiplication of two
tensors.
3. Convert a NumPy array to a PyTorch tensor and a
TensorFlow tensor.

# PyTorch

In [1]:
import torch
import numpy as np

In [2]:
tensor_1d = torch.tensor([1, 2, 3, 4])
print("1D Tensor:\n", tensor_1d)

tensor_2d_random = torch.rand(3, 3)
print("\n2D Random Tensor:\n", tensor_2d_random)

tensor_zeros = torch.zeros(2, 5)
print("\nZeros Tensor:\n", tensor_zeros)

1D Tensor:
 tensor([1, 2, 3, 4])

2D Random Tensor:
 tensor([[0.8325, 0.5483, 0.3957],
        [0.3123, 0.1513, 0.6587],
        [0.0656, 0.5841, 0.5093]])

Zeros Tensor:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [3]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)


Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])


In [4]:
np_array = np.array([[1, 2], [3, 4]])
torch_tensor = torch.from_numpy(np_array)
print("\nNumPy to PyTorch:\n", torch_tensor)


NumPy to PyTorch:
 tensor([[1, 2],
        [3, 4]])


# TensorFlow

In [5]:
import tensorflow as tf
import numpy as np

In [6]:
tensor_1d = tf.constant([1, 2, 3, 4])
print("1D Tensor:\n", tensor_1d)

tensor_2d_random = tf.random.uniform((3, 3))
print("\n2D Random Tensor:\n", tensor_2d_random)

tensor_zeros = tf.zeros((2, 5))
print("\nZeros Tensor:\n", tensor_zeros)

1D Tensor:
 tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

2D Random Tensor:
 tf.Tensor(
[[0.07759738 0.82398415 0.29833388]
 [0.16001701 0.5821258  0.6184313 ]
 [0.35724044 0.27460527 0.5745534 ]], shape=(3, 3), dtype=float32)

Zeros Tensor:
 tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(2, 5), dtype=float32)


In [7]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)


Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [8]:
np_array = np.array([[1, 2], [3, 4]])
tf_tensor = tf.convert_to_tensor(np_array)
print("\nNumPy to TensorFlow:\n", tf_tensor)


NumPy to TensorFlow:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


# Module 2: Automatic Differentiation
### Assignment 2: Gradient Computation
1. Create a tensor x with value 5.0 and set requires_grad=True
(PyTorch) or use tf. GradientTape (TensorFlow).
2. Compute the function y=x2+3x+2y.
3. Calculate the gradient dydx\frac{dy}{dx}.


# Pytorch

In [10]:
x = torch.tensor(5.0, requires_grad=True)
y = x**2 + 3*x + 2
y.backward()
print("dy/dx:", x.grad)

dy/dx: tensor(13.)


# TensorFlow

In [11]:
x = tf.Variable(5.0)
with tf.GradientTape() as tape:
    y = x**2 + 3*x + 2
dy_dx = tape.gradient(y, x)
print("dy/dx:", dy_dx.numpy())

dy/dx: 13.0
